# sudo: false
# dist: trusty

# language: node_js
# node_js:
#   - "8"

# addons:
#   chrome: stable

# cache:
#   yarn: true

# install:
#   - yarn

# before_script:
#   - yarn webdriver:update

# script:
#   - yarn build:prod
#   - yarn lint
#   - yarn test:headless
#   - yarn e2e

# deploy:
#   skip_cleanup: true
#   provider: firebase
#   token:
#     secure: $FIREBASE_TOKEN
#   project: "audiobook-club"

# notifications:
#   email:
#     on_failure: change
#     on_success: change
language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change