# sudo: false
# dist: trusty

# addons:
#   chrome: stable

# before_script:
#   - yarn webdriver:update

# script:
#   - yarn build:prod
#   - yarn lint
#   - yarn test:headless
#   - yarn e2e

# deploy:
#   skip_cleanup: true
#   provider: firebase
#   token:
#     secure: $FIREBASE_TOKEN
#   project: "audiobook-club"

language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - yarn run prod:build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change