language: node_js

node_js:
  - node

env:
  - DISPLAY=:99.0

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  yarn: true
  directories:
    - ./node_modules

before_install:
  - sh -e /etc/init.d/xvfb start

install:
  - yarn install

script:
  - yarn run build -- --prod --aot
  - yarn run lint
  - yarn run test -- --single-run
  - yarn run e2e

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change