language: node_js
node_js: "8"

addons:
  chrome: stable

cache:
  yarn: true
  directories: node_modules

before_script: yarn run webdriver:update

script:
  - yarn run build:prod
  - yarn run lint
  - yarn run test:headless
  - yarn run e2e

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "audiobook-club"
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change