sudo: false
dist: trusty

language: node_js
node_js:
  - "8"

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn webdriver-manager update

script:
  - yarn build -- --prod --aot
  - yarn lint
  - yarn test
  - yarn e2e

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change