sudo: required
dist: trusty

language: node_js
node_js: "8"

addons:
  chrome: stable

cache:
  yarn: true
  directories: node_modules

before_script: yarn webdriver:update

script:
  - yarn build:prod
  - yarn lint
  - yarn test:headless
  - yarn e2e
  - cat coverage/lcov.info | yarn coveralls

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "audiobook-club"
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change