# sudo: false
# dist: trusty

# addons:
#   chrome: stable

# before_script:
#   - yarn webdriver:update

# script:
#   - yarn lint
#   - yarn test:headless
#   - yarn e2e

language: node_js
node_js: "8"

cache:
  yarn: true
  directories: node_modules

branches:
  only: master

install: yarn install

script: yarn run build:prod

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "audiobook-club"
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change