sudo: false
dist: trusty

language: node_js
node_js:
  - "8"

addons:
  chrome: stable

install:
  - yarn

before_script:
  - yarn webdriver:update

script:
  - yarn build:prod
  - yarn lint
  - yarn test:headless
  - yarn e2e

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "audiobook-club"

notifications:
  email:
    on_failure: change
    on_success: change