sudo: false
dist: trusty

language: node_js
node_js:
  - "8"

addons:
  chrome: stable

cache:
  yarn: true

install:
  - yarn

before_script:
  - yarn webdriver:update

script:
  - yarn build:prod
  - yarn lint
  - yarn test:headless
  - yarn e2e

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

deploy:
  skip_cleanup: true

notifications:
  email:
    on_failure: change
    on_success: change